### ISSUE TITLE
d.ts files not resolved

### ISSUE THREAD

**Issue by shroomist** [thundra-io/thundra-agent-nodejs#58]
declaration files reside in `node_modules/@thundra/core/dist/dist` and are not resolved by tsc.
seems like webpack script is breaking this.

**Comment by elgordino** [comment]
Are there plans to address this? It's a shame this typescript project does not have published types.

**Comment by serkan-ozal** [comment]
Fixed by https://github.com/thundra-io/thundra-agent-nodejs/pull/249
